CREATE TABLE user (
	id			VARCHAR(36) PRIMARY KEY,
	username	VARCHAR(50) NOT NULL UNIQUE,
	password	VARCHAR(50) NOT NULL,
	email		VARCHAR(50) NOT NULL
);

CREATE TABLE stored_item (
	id			VARCHAR(36) PRIMARY KEY,
	name		VARCHAR(50) NOT NULL,
	description	VARCHAR(100),
	created		DATETIME DEFAULT NOW NOT NULL,
	modified	DATETIME DEFAULT NOW NOT NULL,
	user_id		VARCHAR(36) NOT NULL,
	website		VARCHAR(100) NOT NULL,
	password	VARCHAR(50)	NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);
